# 端口哦
server:
  port: 8080

# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# 日志
logging:
  level:
    root: info
    com.ivan: debug
  file:
    name: springboot.log


# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 数据库自增
      table-prefix: mp_
      table-underline: true
  type-aliases-package: com.ivan.bean
